# .github/workflows/swagger.yml
name: Generate and Deploy Swagger Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  swagger:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Generate swagger docs
        run: swag init -g main.go -o ./docs

      - name: Create docs directory for GitHub Pages
        run: |
          mkdir -p gh-pages
          cp docs/swagger.json gh-pages/
          cp docs/swagger.yaml gh-pages/

      - name: Create index.html
        run: |
          cat > gh-pages/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <title>CleanEase API Documentation</title>
            <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
            <link rel="stylesheet" type="text/css" href="https://unpkg.com/swagger-ui-dist@4.15.5/swagger-ui.css" />
            <style>
              html { box-sizing: border-box; overflow: -moz-scrollbars-vertical; overflow-y: scroll; }
              *, *:before, *:after { box-sizing: inherit; }
              body { margin:0; background: #fafafa; }
              .info { padding: 20px; background: #fff3cd; border: 1px solid #ffeaa7; margin: 20px; border-radius: 5px; }
            </style>
          </head>
          <body>
            <div class="info">
              <h3>⚠️ Development Notice</h3>
              <p><strong>API Server:</strong> Make sure your local API is running on <code>http://localhost:8080</code></p>
              <p><strong>CORS:</strong> You may need to allow mixed content in your browser for HTTPS → HTTP requests</p>
              <p><strong>Chrome:</strong> Click the shield icon in address bar → "Load unsafe scripts"</p>
              <p><strong>Firefox:</strong> Click the shield icon → "Disable protection for now"</p>
            </div>
            
            <div id="swagger-ui"></div>
            
            <script src="https://unpkg.com/swagger-ui-dist@4.15.5/swagger-ui-bundle.js"></script>
            <script src="https://unpkg.com/swagger-ui-dist@4.15.5/swagger-ui-standalone-preset.js"></script>
            <script>
              window.onload = function() {
                const ui = SwaggerUIBundle({
                  url: './swagger.json',
                  dom_id: '#swagger-ui',
                  deepLinking: true,
                  presets: [
                    SwaggerUIBundle.presets.apis,
                    SwaggerUIStandalonePreset
                  ],
                  plugins: [
                    SwaggerUIBundle.plugins.DownloadUrl
                  ],
                  layout: "StandaloneLayout",
                  // Force HTTP for localhost
                  requestInterceptor: function(request) {
                    // Log request untuk debugging
                    console.log('Making request to:', request.url);
                    return request;
                  },
                  responseInterceptor: function(response) {
                    // Log response untuk debugging
                    console.log('Response:', response.status, response.url);
                    return response;
                  }
                });
              };
            </script>
          </body>
          </html>
          EOF
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
          force_orphan: true
